[network]
servers = ["35.210.235.17:80"]

[player]
name = "Arne"
team = "blue"
avatar = 1

[controls]
forward = 'e'
left = 's'
backward = 'd'
right = 'f'
jump = ' '
mouse_sensitivity = 100

[graphics]
width = 1280
height = 768
fullscreen = false
no_msaa = false
anisotropy = 8
texture_resolution = 512
no_normal_maps = false
no_textures = false
lightmap_nearest = false
no_mipmaps = false
no_trilinear = false
vsync = true

[sound]
enabled = true
volume = 100
